### ISSUE TITLE
Object() vs Array() detection in AHK v1

### ISSUE THREAD

**Issue by TheArkive** [Shambles-Dev/AutoHotkey-Type_Checking#1]
This is a VERY nice lib for AHK v1.  Thanks for writing this.  I'd like to offer one extra bit for detecting Object() vs Array().

I know this isn't perfect, because of the bizarre chimera objects that are possible in AHK v1, but if objects conform to AHK v2 specifications for Map() and Array() then this will work:

```
Type(Value) {
    local
    global _Type
    
    static BoundFunc             := Func("Type").Bind("")
    static ComObjArrayEnumerator := ComObjArray(0x11, 1)._NewEnum()
    static ComObjectEnumerator   := ComObjCreate("Scripting.Dictionary")._NewEnum()
    static File                  := FileOpen(A_ScriptFullPath, "r")
    static Func                  := Func("Type")
    static ObjectEnumerator      := {}._NewEnum()
    static Property              := ObjRawGet(_Type, "Property")
    static RegExMatch, _         := RegExMatch("a" ,"O)a", RegExMatch)
    Static Obj                   := Object() ; <--- add this type
    
    static TypeFromAddress := {NumGet(&BoundFunc):             "BoundFunc"expressions 
                              ,NumGet(&ComObjArrayEnumerator): "ComObjArray.Enumerator"
                              ,NumGet(&ComObjectEnumerator):   "ComObject.Enumerator"
                              ,NumGet(&File):                  "File"
                              ,NumGet(&Func):                  "Func"
                              ,NumGet(&ObjectEnumerator):      "Object.Enumerator"
                              ,NumGet(&Property):              "Property"
                              ,NumGet(&RegExMatch):            "RegExMatch"
                              ,NumGet(&Obj):                   "Object"} ; add corresponding value
    
    if (IsType("object", Value)) {
        if (TypeFromAddress.HasKey(NumGet(&Value))) {
            Result := TypeFromAddress[NumGet(&Value)]
            
            If (Result = "object") And (Value.Length()=Value.Count()) ; if .Length() and .Count() are equal,
                Result := "Array"                                     ; then it is a legit array.
```

Of course if the base object has no elements, it is near impossible to detect if it was spawned with `[]` or `{}` / `Object()`.

This application is slightly narrow.  Mostly for use with serializing objects, like in JSON.  This would mostly apply to only linear arrays and associative arrays.

**Comment by Shambles-Dev** [comment]
There is 'no difference' between Objects and Arrays in AutoHotkey v1.  I put 'no difference' in scare quotes because there are obviously things you can do with (genuine) Arrays (like reverse or sort them) that do not make sense with arbitrary Objects.

If you try to compare implementation pointers, they will compare the same.

Your tests would be inadequate for other reasons.  Consider an Object with the keys "1", "3", and "a".  The length (highest integer key) is 3.  The count (number of items) is 3.  But it is still not a genuine Array.

The only way I know of to detect genuine Arrays is the extremely inefficient process of checking that every key between 1 and the length exists and then checking that the length matches the count to rule out the existence of other keys.  This assumes that the Array is equivalent to a 'genuine array', as in it has no missing elements and therefore has the semantics of arrays in well-designed programming languages.  Sadly, AutoHotkey sometimes requires using Arrays with missing elements (e.g. invoking default behavior in built-in functions or methods via a 'variadic call' (a.k.a. application)).

Also, as you mentioned, the case of an empty Object and an empty Array is truly ambiguous, with no way to resolve it other than context.

I do not plan on adding the feature you request for those reasons.

If your interest is in (de)serializing objects for AutoHotkey v1 or JavaScript, this library will work as is.  Both languages made the mistake of conflating objects and dictionaries, and dictionaries and arrays.

**Comment by TheArkive** [comment]
```
Your tests would be inadequate for other reasons. Consider an Object with the keys "1", "3", and "a". The length (highest integer key) is 3. The count (number of items) is 3. But it is still not a genuine Array.
```

This is actually not accurate.  The constraints on "genuine arrays" in AHK v2 are easy to check in AHK v1.  Replicating your example with a little more detail:

```
test := Object("1","a","2","b","3","c")
msgbox % test.Length() " / " test.count()

test := Object(1,"a",2,"b","3","c")
msgbox % test.Length() " / " test.count()

test := Object(1,"a",2,"b",3,"c")
msgbox % test.Length() " / " test.count()

test := ["a","b","c"]
msgbox % test.Length() " / " test.Count()
```

The first msgbox returns [ length = 0 / count = 3 ], because all keys were passed as strings.

The 2nd msgbox returns [ length = 2 / count = 3 ], because 2 keys were passed as numerical.

The 3rd msgbox returns [ length = 3 / count = 3 ], this is "as good as a genuine array" for all intents and purposes with AHK v1.

The 4th msgbox returns [ length = 3 / count = 3 ], because .count() will talley all numerical and string keys.

You can add string keys to Arrays() and you can add numerical keys to Objects(), not perfect, but still not outside the realm of some control.

In your example, assuming the first 2 keys are passed as actually numerical, then .length() should return 2, and .count() should return 3.

It also depends on how you apply those keys.  If you manually add all those keys as "strings", then .Length() would return 0, and .count() would return 3.  Of course if you have a numerical "string" in a var, and pass it as a key for an array, then it will be translated as a numerical key, which is a defect / "feature of simplicity" of AHK v1.  But the main point still stands, a "genuine array" will have no gaps in the keys, and in the case of a genuine array, .Length() = .Count().

In either case, i have been trying to expand libraries that are either compatible for both AHK v1 / v2, or I'm converting / creating libraries for AHK v1 / v2.  Is it ok if I post a modified version of your code with my libraries?  I have been searching for a good means of type detection in AHK v1 and currently yours is by far the best.

**Comment by Shambles-Dev** [comment]
A genuine array is a strip of memory containing elements indexed via (0-based in good designs) consecutive integers relative to the first element.  AutoHotkey v1 and v2 do not use genuine arrays.  They abuse a dictionary as an Object and Array (and 'Map' (a.k.a. dictionary) in v2).  They appear to have directly copied the mistake from JavaScript, syntax and all.

`{1: "foo", "a": "bar", 3: "baz"}` has a Count of 3 and a Length of 3 but is most certainly not a genuine array, even in the abstract 'it can be reliably (though inefficiently) used as if it was one' way.

Recall that there is no difference between numbers and strings in v1.  v2 still has them conflated, but in a more complex, and probably more dangerous, way.  In a language designed for novices, everything should have been an object (so novices are not constantly having to figure out how to detect and work around some broken commonly used types), and types that are not substitutable (you cannot divide "castle" by 3, but you can divide 5 by 3) should be implemented as (fully) distinct types without coercion.

Some algorithms will work reliably with excess or missing keys.  However, others (like reverse and sort) will not.  Facade, a much more complex library built atop this one, contains algorithms that only work with data structures that can be reliably used as if they were genuine arrays.

I will not add further confusion to the issue by making this library call things Arrays which are not arrays in either the 'initially constructed as' or 'reliably usable as' sense.

This library is released under the LGPL.  Therefore, I cannot prevent you from forking it.  However, you will have to credit all code you copied from me, I do not approve of forking it for this purpose, and I will not support it.

v2 is constantly changing, and I have several thousand non-comment, non-whitespace lines of AutoHotkey code (e.g. Facade is about 5,000) to maintain, so I am not interested in running on that treadmill.  I might port my libraries to it once it has been officially released.  I have attempted to design them with that in mind.

This library should be of minimal use in v2 anyway.  It exists because v1 provides neither a coherent type system nor consistent interfaces to allow user-defined types to be used like built-in types.  Further, v1 attempts to ignore errors, and this library is useful for predicting if an error would occur were an operation attempted.  Its code would be trivial in v2 because most of it is as direct a backport of v2 features as possible.

**Comment by TheArkive** [comment]
Right my bad, forgot about the "missing key gaps" that AHK v1 allows, thus adding the necessity to check all keys (at least up to the first key that doesn't equal A_Index...).  And regarding "genuine arrays", I was referring to the current v2 specification of the Array `[]` type, not arrays from other languages.

My intent was only to use this with AHK v1.  I find AHK v2 Type() function sufficient for my uses.

Of course I will credit you.  I do this on all my work based on other's work.  And no worries about me pestering you for support.  Your code makes sense to me, and I'm capable of learning about the details I haven't fully grasped yet.

I do sympathize with your frustrations of AHK v1, and with the rapid changes of AHK v2.  I just think a few more boundaries are needed in AHK v1 when it comes to Arrays() and Objects(), even if those boundaries are somewhat or completely arbitrary.  I think these boundaries are particularly necessary when trying to preserve functionality between different versions of AHK scripts.

Thanks again for your work on this.  The lacking type-detection in v1 has driven me batty for a while.  Yours is still the best there is for v1.

**Comment by Shambles-Dev** [comment]
According to my tests, Array has the same problems in v2 as v1.  There is some newspeak in the manual about how 'missing elements are inserted', but when one goes looking for the emperor's new clothes, one finds 'Has' says they do not exist.

At least that leaves me with a (slow) way of detecting broken arrays in v2.

Hopefully, someday we can compile or interpret an acceptable language atop AutoHotkey and be rid of AutoHotkey's awful programming language.

**Comment by TheArkive** [comment]
You will hopefully be pleased to know that Arrays and Maps in AHK v2 are much more strict.

If you try to modify an element (that doesn't exist) ... ex:   `arr[3] := value` ... then you will get an error in AHK v2 a122.  The only way to add an element to a legit AHK v2 array is `.Push()` or `.InsertAt()` ... gaps don't happen in AHK v2 as far as I'm able to tell.

And of course the Type() function accurately detects Maps and Arrays separately, and Objects `{}` are also a separate type.

**Comment by Shambles-Dev** [comment]
I tested v2's Array myself.  There are no improvements that are useful to me.  Missing elements should not exist as a concept.  So long as they do, array semantics do not hold.  Type() lying that something with missing elements is an array, if anything, makes it worse.  When missing elements can exist, basic functionality like proper array reversing (that does not change the length of the array) and sorting (you cannot compare 'missing' to something) cannot be provided.  Facade copes by considering AutoHotkey arrays to not be real arrays until they have been demonstrated to not have missing elements (via the inefficient algorithm I explained).

To correct this design flaw, AutoHotkey would need to adopt a null value (to take the place of missing keys to imply default behavior during application) and to combine allocation and initialization (to ensure uninitialized values cannot exist).  You know, like most programming languages invented since at least 1970.

The misuse of common dictionary syntax for 'object literals' (another concept that should not exist) is another slap in the face.  It prevents it from being used for proper dictionaries.  And don't get me started on v2's notion of case-insensitive dictionaries (something that do not exist elsewhere for very good reasons involving basic data structures and algorithms).  And of course they had to name it "Map", which normally means a common functional programming function for computing a new sequence from a function and an existing sequence, instead of "Dict" or anything else sensible.

Hopefully my libraries embarrass the devs into accepting functionality almost (JavaScript and PHP exist) every other non-joke programming language takes for granted.  If not, at least I can program atop them and pretend the language is sane most of the time.

**Comment by Shambles-Dev** [comment]
If you still intend to derive code from mine, please use this as your inspiration https://github.com/Shambles-Dev/AutoHotkey-New_Type_Checking  It is more powerful and slightly faster.

I hope to eventually reimplement my other code atop it and update this repository with its contents.

**Comment by Shambles-Dev** [comment]
Also, if you are going to try to guess types in ambiguous situations, know that more is conflated than Object and Array in v1.  Object and Exception are also conflated in v1.  Object and Property are conflated in v2, and that is a recent development.

**Comment by TheArkive** [comment]
Ok thanks I'll take a look at that.  And thanks for the heads up about those other objects.
